In [39]:
import pandas as pd
import json 
import re
import numpy as np
import cirpy
import rdkit
import pandas as pd 

from tqdm import tqdm

import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem

from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole

from rdkit.Chem import PandasTools
import seaborn as sns
import matplotlib.pyplot as plt
from rdkit import Chem
from tqdm.notebook import tqdm
tqdm.pandas()

In [40]:
DyeData = pd.read_csv("/home/matt/Proj/Dyes/Dyebrary/DyeScraping/StructuredWDVDyeData.csv")

# Extract the CAS numbers from structured text

In [41]:
# make a small function to extract CAS number from the text
def getCAS(txt):
    try: 
        casnum = re.search('CAS Registry Number:(.*)',txt)
        cas = casnum.groups()[0]
    except:
        cas = None
    return cas

In [42]:
DyeData['CASNumber'] = DyeData['CAS'].apply(getCAS)

In [43]:
DyeData['CAS'] = DyeData['CASNumber']
DyeData=DyeData.drop(['CASNumber'],axis=1)

In [44]:
DyeData

,name,CAS,LF,Standard,Dyetype,class,properties
0,"Name:C.I.Acid Red 92,C.I. 45410",18472-87-2,3,AATCC,AcidDye,Molecular Structure: Xanthene,Properties and Applications: brilliant pink. S...
1,"Name:C.I.Acid Brown 32,C.I. 23000",6375-57-1,4,ISO,AcidDye,Molecular Structure: Double azo,Properties and Applications: red light brown. ...
2,"Name:C.I.Acid Black 242,C.I.30028",152521-111-4,4,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...
3,"Name:C.I.Acid Black 241,C.I.30024",84170-03-6,4-5,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...
4,Name:C.I.Acid Black 237,None,4-5,ISO,AcidDye,"Molecular Structure: azo,1:2 Metal Complexes",Properties and Applications: green light grey....
...,...,...,...,...,...,...,...
2986,"Name:C.I.Solubilised Vat Yellow 3 ,C.I.61726",6711-83-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow.
2987,"Name:C.I.Vat Yellow 3,C.I.61725",82-18-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow. Yellow p...
2988,"Name:C.I.Solubilised Vat Yellow 2,C.I.67301",13109-68-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yellow.
2989,"Name:C.I.Vat Yellow 2,C.I.67300",129-09-9,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yello...
2990,"Name:C.I.Solubilised Vat Yellow 1,C.I.70601",6487-09-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: red light yellow.

In [45]:
# make a quick function to get the SMILES of each molecule
# for CAS ref
def resolve(x):
    try:
        z = cirpy.resolve(x, 'smiles')
    except:
        z = None
    return z

In [46]:
DyeData['SMILES'] = DyeData['CAS'].progress_apply(resolve)

  0%|          | 0/2991 [00:00<?, ?it/s]

In [51]:
DyeData.to_csv('/home/matt/Proj/Dyes/Dyebrary/DyeScraping/WDVSMILESExtracted.csv')

# Extract the Properties of the Dye from Text

In [47]:
DyeData

,name,CAS,LF,Standard,Dyetype,class,properties,SMILES
0,"Name:C.I.Acid Red 92,C.I. 45410",18472-87-2,3,AATCC,AcidDye,Molecular Structure: Xanthene,Properties and Applications: brilliant pink. S...,[Na+].[Na+].[O-]c1c(Br)cc2c(Oc3c(Br)c([O-])c(B...
1,"Name:C.I.Acid Brown 32,C.I. 23000",6375-57-1,4,ISO,AcidDye,Molecular Structure: Double azo,Properties and Applications: red light brown. ...,None
2,"Name:C.I.Acid Black 242,C.I.30028",152521-111-4,4,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...,None
3,"Name:C.I.Acid Black 241,C.I.30024",84170-03-6,4-5,ISO,AcidDye,Molecular Structure: trisazo class,Properties and Applications: black. Mainly use...,None
4,Name:C.I.Acid Black 237,None,4-5,ISO,AcidDye,"Molecular Structure: azo,1:2 Metal Complexes",Properties and Applications: green light grey....,None
...,...,...,...,...,...,...,...,...
2986,"Name:C.I.Solubilised Vat Yellow 3 ,C.I.61726",6711-83-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow.,[Na+].[Na+].[O-][S](=O)(=O)Oc1c2cccc(NC(=O)c3c...
2987,"Name:C.I.Vat Yellow 3,C.I.61725",82-18-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: yellow. Yellow p...,O=C(Nc1cccc2C(=O)c3c(NC(=O)c4ccccc4)cccc3C(=O)...
2988,"Name:C.I.Solubilised Vat Yellow 2,C.I.67301",13109-68-7,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yellow.,None
2989,"Name:C.I.Vat Yellow 2,C.I.67300",129-09-9,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: green light yello...,O=C1c2ccc3nc(sc3c2C(=O)c4ccc5nc(sc5c14)c6ccccc...
2990,"Name:C.I.Solubilised Vat Yellow 1,C.I.70601",6487-09-8,5,ISO,VatDye,Molecular Structure: anthraquinones,Properties and Applications: red light yellow.,None

2991

In [6]:
# for CAS ref
def resolve(x):
    z = cirpy.resolve(x, 'smiles')
    return z

In [7]:
df = pd.DataFrame(CAS)

In [8]:
df['SMILES'] = df[0].progress_apply(resolve)

  0%|          | 0/230 [00:00<?, ?it/s]

In [9]:
df

              0                                             SMILES
0    12227-17-7                                               None
1    12237-35-3                                               None
2     6424-66-4                                               None
3    61902-44-1                                               None
4     6049-19-0                                               None
..          ...                                                ...
225   6711-83-7  [Na+].[Na+].[O-][S](=O)(=O)Oc1c2cccc(NC(=O)c3c...
226     82-18-8  O=C(Nc1cccc2C(=O)c3c(NC(=O)c4ccccc4)cccc3C(=O)...
227  13109-68-7                                               None
228    129-09-9  O=C1c2ccc3nc(sc3c2C(=O)c4ccc5nc(sc5c14)c6ccccc...
229   6487-09-8                                               None

[230 rows x 2 columns]

In [10]:
df = df.dropna()

In [11]:
df

              0                                             SMILES
5      128-79-0  O=C(Nc1ccc(Nc2ccc(NC(=O)c3ccccc3)c4C(=O)c5cccc...
6    23594-58-3  [Na+].[Na+].[Na+].[Na+].[O-][S](=O)(=O)Oc1c2cc...
12   34599-04-7  [Na+].[Na+].[Na+].[Na+].[O-][S](=O)(=O)OC1=CC=...
13    2278-50-4  O=C1c2ccccc2C(=O)c3c4[nH]c5ccc6c7ccc8n9nc%10c%...
15   10169-52-5  [Na+].[Na+].[O-][S](=O)(=O)Oc1c([nH]c2ccccc12)...
..          ...                                                ...
223   3564-70-3  [Na+].[Na+].[O-][S](=O)(=O)Oc1c2ccccc2c3ccc4c(...
224    128-66-5         O=C1c2ccccc2c3ccc4C(=O)c5ccccc5c6ccc1c3c46
225   6711-83-7  [Na+].[Na+].[O-][S](=O)(=O)Oc1c2cccc(NC(=O)c3c...
226     82-18-8  O=C(Nc1cccc2C(=O)c3c(NC(=O)c4ccccc4)cccc3C(=O)...
228    129-09-9  O=C1c2ccc3nc(sc3c2C(=O)c4ccc5nc(sc5c14)c6ccccc...

[110 rows x 2 columns]

In [12]:
# fucntion to do all that 


def CAStoSMILES(name):
    Dyes =open('{}Dyes.json'.format(name))
    Raw = json.load(Dyes)
    

    CAS = []

    for i in range(0,len(Raw)):
        try:
            casStr = acidRaw[i]['verbal']['CAS']

            cas = re.search('CAS Registry Number:(.*)',casStr)

            casnum = cas.groups()[0]
        except:
            continue

        CAS.append(casnum)

    df = pd.DataFrame(CAS)

    df['SMILES'] = df[0].apply(resolve)

    df = df.dropna()

    df.to_csv('data/{}.csv'.format(name),index=False)
    print(('{}Dyes:'.format(name),len(df)))

In [13]:
names= ['acid' ,'azoic','basic','direct','disperse','food','mordant','reactive','solvent','sulfur','vat']

In [14]:
for name in names:
    CAStoSMILES(name)

('acidDyes:', 110)
('azoicDyes:', 38)
('basicDyes:', 68)
('directDyes:', 110)
('disperseDyes:', 110)
('foodDyes:', 19)
('mordantDyes:', 108)
('reactiveDyes:', 110)
('solventDyes:', 110)

KeyError: 0

In [ ]:
CAStoSMILES('vat')

('vatDyes:', 110)